# Reviewer를 PR에 추가하고자 할 때 true로 설정하세요.
addReviewers: true

# Assignee를 PR에 추가하고자 할 때 true로 설정하세요.
addAssignees: false

# PR에 추가된 reviewer의 수
# 0으로 설정해 모든 reviewer를 추가할 수 있습니다 (기본값: 0)
numberOfReviewers: 1

# PR에 추가된 assignee의 수
# 0으로 설정해 모든 assignee를 추가할 수 있습니다.
# 설정되어 있지 않은 경우 numberOfReviewers를 사용합니다.
# numberOfAssignees: 2

# Set to true to add reviewers from different groups to pull requests
# true로 설정하여 다른 그룹으로부터 PR에 reviewer를 추가할 수 있습니다.
useReviewGroups: true

# Reviewer를 그룹으로 나눌 수 있습니다.
# GitHub username을 사용합니다.
reviewGroups:
  groupA:
    - terytory
    # - reviewerB
    # - reviewerC
  groupB:
    # - reviewerD
    # - reviewerE
    # - reviewerF

# true로 설정하여 다른 그룹으로부터 PR에 assignee를 추가할 수 있습니다.
useAssigneeGroups: false

# Assignee를 그룹으로 나눌 수 있습니다.
# GitHub username을 사용합니다.
# assigneeGroups:
#   groupA:
#     - assigneeA
#     - assigneeB
#     - assigneeC
#   groupB:
#     - assigneeD
#     - assigneeE
#     - assigneeF

# 특정 키워드가 포함돼 있을 때 Reviewer를 추가하지 않도록 하는 키워드입니다.
# skipKeywords:
#   - wip

# Author로 설정하여 PR 생성자를 assignee로 설정합니다.
addAssignees: author